//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BO
    {
        public long id { get; set; }
        public string Bo_number { get; set; }
        public string amount { get; set; }
        public string grbs { get; set; }
        public string kcsr { get; set; }
        public string kesr { get; set; }
        public string kfsr { get; set; }
        public string kvr { get; set; }
        public string period { get; set; }
        public Nullable<long> id_agreement_org { get; set; }
    
        public virtual AGREEMENT_ORG AGREEMENT_ORG { get; set; }
    }
}
