//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProITEntities : DbContext
    {
        public ProITEntities()
            : base("name=ProITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<AGREEMENT> AGREEMENT { get; set; }
        public virtual DbSet<AGREEMENT_ORG> AGREEMENT_ORG { get; set; }
        public virtual DbSet<BO> BO { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULE { get; set; }
    }
}
