//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public Nullable<System.DateTime> transferDate { get; set; }
        public string transferSumm { get; set; }
        public Nullable<long> id_agreement_org { get; set; }
        public long id { get; set; }
    
        public virtual AGREEMENT_ORG AGREEMENT_ORG { get; set; }
    }
}
